# Generated by Django 4.2.7 on 2023-11-01 15:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ESblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog',
            new_name='ESblog',
        ),
    ]
